# workflow for checking package versions and opening PRs to bump
name: Renovate
on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
  workflow_call:

jobs:
  renovate:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@a889a8abcb11ef7feaafaf5e483ea01d4bf7774e # v43.0.5
        with:
          configurationFile: .github/renovate-config.js
          token: ${{ github.token }}
